### ISSUE TITLE
dev fails because of astro

### ISSUE THREAD

**Issue by Jessewb786** [event-catalog/eventcatalog#1064]
### I tried this:

Tried to run `"dev": "eventcatalog dev"` on a clean event-catalog after an `npm install`.

The issue seems to be regarding @astrojs/mdx not being imported.

### This happened:

```
/Users/john_doe/.nvm/versions/node/v20.16.0/bin/npm run dev

> event-catalog@0.1.0 dev
> eventcatalog dev

Setting up EventCatalog....
EventCatalog is starting at http://localhost:3000/docs
[astro] 11:21:17 AM [vite] Error when evaluating SSR module /Users/john_doe/Project/event-catalog/.eventcatalog-core/astro.config.mjs: failed to import "@astrojs/mdx"
[astro] |- Error: Cannot find module '@astrojs/mdx' imported from '/Users/<user>/Project/event-catalog/.eventcatalog-core/astro.config.mjs'
[astro]     at nodeImport (file:///Users/<user>/Project/event-catalog/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:53047:19)
[astro]     at ssrImport (file:///Users/john_doe/Project/event-catalog/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:52914:22)
[astro]     at eval (/Users/john_doe/Project/event-catalog/.eventcatalog-core/astro.config.mjs:5:37)
[astro]     at async instantiateModule (file:///Users/john_doe/Project/event-catalog/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:52972:5)
[astro] 
[astro] [astro] Unable to load your Astro config
[astro] 
[astro] Cannot find module '@astrojs/mdx' imported from '/Users/john_doe/Project/event-catalog/.eventcatalog-core/astro.config.mjs'
[astro]   Location:
[astro]     /Users/john_doe/Project/event-catalog/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:53047:19
[astro]   Stack trace:
[astro]     at nodeImport (file:///Users/john_doe/Project/event-catalog/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:53047:19)
[astro]     at eval (/Users/john_doe/Project/event-catalog/.eventcatalog-core/astro.config.mjs:5:37)
[astro] npx astro dev  exited with code 1
[
  {
    command: Command {
      close: [Subject],
      error: [Subject],
      stdout: [Subject],
      stderr: [Subject],
      timer: [Subject],
      killed: false,
      exited: true,
      index: 0,
      name: 'astro',
      command: 'npx astro dev ',
      prefixColor: '',
      env: [Object],
      cwd: '/Users/john_doe/Project/event-catalog/.eventcatalog-core',
      killProcess: [Function (anonymous)],
      spawn: [Function (anonymous)],
      spawnOpts: [Object],
      process: undefined,
      pid: 79660,
      stdin: [Socket]
    },
    index: 0,
    exitCode: 1,
    killed: false,
    timings: {
      startDate: 2024-12-20T10:21:15.482Z,
      endDate: 2024-12-20T10:21:17.537Z,
      durationSeconds: 2.054959167
    }
  }
]

Process finished with exit code 0
```

### I expected this:

I, of course, expected the service to start-up normally on port 3000.

### EventCatalog Version

"@eventcatalog/core": "2.18.5"

### Node.js Version

v20.16.0

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by boyney123** [comment]
Hey @Jessewb786 

Thanks for sharing this.

We have seen a few issues with this recently ([check on Discord for convo](https://discord.com/channels/918092420338569216/1318937085822111794))

Can you try this https://www.eventcatalog.dev/docs/development/guides/upgrading#having-problems

(Delete node_modules, lock files, .eventcatalog-core) and try again?

**Comment by Jessewb786** [comment]
@boyney123 Unfortunately, after trying that, I still get the following:
```
Setting up EventCatalog....
EventCatalog is starting at http://localhost:3000/docs
[astro] 14:51:31 [types] Generated 1ms
[astro] 14:51:31 [WARN] [vite] Failed to resolve dependency: react-compiler-runtime, present in client 'optimizeDeps.include'
[astro] 14:51:31 [ERROR] [UnhandledRejection] Astro detected an unhandled rejection. Here's the stack trace:
[astro] TypeError: fsevents.watch is not a function
[astro]     at createFSEventsInstance (file:///Users/john_doe/Project/event-catalog/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:28338:25)
[astro]     at setFSEventsListener (file:///Users/john_doe/Project/event-catalog/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:28394:16)
[astro]     at FsEventsHandler._watchWithFsEvents (file:///Users/john_doe/Project/event-catalog/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:28598:18)
[astro]     at FsEventsHandler.initWatch (file:///Users/john_doe/Project/event-catalog/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:28674:23)
[astro]     at FsEventsHandler._addToFsEvents (file:///Users/john_doe/Project/event-catalog/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:28763:12)
[astro]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[astro]   Hint:
[astro]     Make sure your promises all have an `await` or a `.catch()` handler.
[astro]   Error reference:
[astro]     https://docs.astro.build/en/reference/errors/unhandled-rejection/
[astro]   Stack trace:
[astro]     at /Users/john_doe/Project/event-catalog/.eventcatalog-core/Users/john_doe/Project/event-catalog/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:28338:25
[astro]     [...] See full stack trace in the browser, or rerun with --verbose.
[astro] 
```

**Comment by eps90** [comment]
I also encountered this problem and I noticed it fails when project's `package.json` has a property `type` set to `module`, as I have some additional scripts there. Having that property on, `npm install` does not install all packages, including `@astrojs/mdx`. Bringing back `package.json` to look the same as the generated one fixes the problem (but doesn't fix ability to use modules in node.js). Tested on the latest `2.18.5` version

**Comment by Jessewb786** [comment]
@eps90 Indeed, and what I find myself having to do is make everything is lazily computed so that when astro starts with the eventcatalog.config.js, it doesn't compute everything.

And then I still have the issue that I have dynamically resolved generators in my eventcatalog.config.js which are not needed when I run dev, so then I have this frankly sad if check:

```
if (scriptDirectory.endsWith(".eventcatalog-core")) {
 return [];
} else {
...
}
```

This lets me run the generate from package.json and also lets me run dev.

I would love to know if there is some other way of integrating dynamically resolved generators. 
And they're dynamically resolved because they rely on a series of folders that contain spec files that are the output of [yamlinc](https://github.com/javanile/yamlinc) which stitches together components that are reused across multiple spec files.

**Comment by boyney123** [comment]
I'm not sure how to replicate this and @carlosallexandre looked too.

Going to close for now, as the latest version of the catalog does not seem to give this error?

If you can find a way we can replicate please feel free to open the issue.

**Comment by eps90** [comment]
@boyney123 My comment above was about the newest version of EventCatalog and I provided an information how to replicate that.

**Comment by boyney123** [comment]
This might help to replicate @carlosallexandre https://github.com/event-catalog/eventcatalog/issues/1064#issuecomment-2566362932?

**Comment by carlosallexandre** [comment]
![image](https://github.com/user-attachments/assets/317befe8-9fc6-4e10-920e-844d6edf2d01)
I tried here without any success. 

@eps90  I tried this way:
1. Run `npx @eventcatalog/create-eventcatalog@latest mdx-test`
2. Delete `node_modules` and `package-lock.json` 
3. Set `type: "module"` on `package.json`
4. Run `npm install`
5. Run `npm run dev`

**Comment by eps90** [comment]
@carlosallexandre Sorry for no response, I send some detailed steps to reproduce on Monday, if that's ok. I'm AFK until then

**Comment by boyney123** [comment]
Thank you @eps90

**Comment by Jessewb786** [comment]
This issue is no longer occurring for me on the latest versions.
I'll let @eps90 handle it from here if it's still an issue.

**Comment by rcdailey** [comment]
Mine isn't working on version 2.19.3, I don't even get error output, dev just exits after 1 second:
```
PS C:\src\eventcatalog\src\ui> npm run dev

> identified-catalog@0.1.0 dev
> eventcatalog dev

Setting up EventCatalog....
EventCatalog is starting at http://localhost:3000/docs
PS C:\src\eventcatalog\src\ui>
```

**Comment by boyney123** [comment]
Strange @rcdailey , are you still having issues?

**Comment by rcdailey** [comment]
@boyney123 Looks like for whatever reason, the `ui` directory is causing some problem. Note from my last message that I have the eventcatalog site under `src/ui` in my git repo. I renamed `ui` to `eventcatalog` (so now the path is `src/eventcatalog`) and now it works fine.

Not sure what the root cause of that was due to lack of logs.

**Comment by boyney123** [comment]
> [@boyney123](https://github.com/boyney123) Looks like for whatever reason, the `ui` directory is causing some problem. Note from my last message that I have the eventcatalog site under `src/ui` in my git repo. I renamed `ui` to `eventcatalog` (so now the path is `src/eventcatalog`) and now it works fine.
> 
> Not sure what the root cause of that was due to lack of logs.

OK interesting, never tried it as a sub directory yet, will try that when I get round to it.

How do you all feel if we close this issue, or is there still issues (stoppers) people are facing?

**Comment by nicolamassarenti** [comment]
Hi @boyney123,

I'm facing the same issue. This is what I have as output

```
❯ npm run dev

> dende@0.1.0 dev
> eventcatalog dev

Setting up EventCatalog....
EventCatalog is starting at http://localhost:3000/docs
[astro] npx astro dev  exited with code 1
[
  {
    command: Command {
      close: [Subject],
      error: [Subject],
      stdout: [Subject],
      stderr: [Subject],
      timer: [Subject],
      killed: false,
      exited: true,
      index: 0,
      name: 'astro',
      command: 'npx astro dev ',
      prefixColor: '',
      env: [Object],
      cwd: '/home/nicola/Documents/dende/dev/event-catalog/.eventcatalog-core',
      killProcess: [Function (anonymous)],
      spawn: [Function (anonymous)],
      spawnOpts: [Object],
      process: undefined,
      pid: 574014,
      stdin: [Socket]
    },
    index: 0,
    exitCode: 1,
    killed: false,
    timings: {
      startDate: 2025-01-31T22:20:34.047Z,
      endDate: 2025-01-31T22:20:37.794Z,
      durationSeconds: 3.7466281649999997
    }
  }
]
```

**Comment by boyney123** [comment]
@nicolamassarenti Very strange, what OS and node version are you using?

**Comment by nicolamassarenti** [comment]
> [@nicolamassarenti](https://github.com/nicolamassarenti) Very strange, what OS and node version are you using?

@boyney123 

- Node: v18.20.6
- OS:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 23.04
Release:	23.04
Codename:	lunar
```

**Comment by megakid** [comment]
I just checked out the asyncapi sample (https://github.com/event-catalog/eventcatalog-asyncapi-example) and ran into this issue out the box

**Comment by jaredrussell** [comment]
Just as an additional data point, I was seeing the same error when trying to run a freshly created empty project. I was using `pnpm` to initialise the repo (e.g. `pnpm dlx @eventcatalog/create-eventcatalog@latest . --empty` followed by `pnpm dev`).

Switching to `npm` resolved the issue.

**Comment by boyney123** [comment]
Thanks @jaredrussell , yeah I don't believe we support `pnpm` at the moment, need to fix/explore why still.

**Comment by boyney123** [comment]
> I just checked out the asyncapi sample (https://github.com/event-catalog/eventcatalog-asyncapi-example) and ran into this issue out the box
> 
> Running node 22.5.1 on Windows

Can you try this when you get a second? https://github.com/event-catalog/generators/tree/main/examples/generator-asyncapi/basic

**Comment by hoghweed** [comment]
Since I had the same issues using `pnpm` I tried enabling in `.npmrc` the shamefully hoisting.

For sure, this is not the best option, at least because you're not using pnpm using all its power. 

Anyway, this is more or less what I've done:

#### 1 - starting with pnpm

`pnpx @eventcatalog/create-eventcatalog@latest my-catalog`

#### 2 - enable in `.npmrc`

```
shamefully-hoist=true
```

#### 3 - delete the node_modules folder

#### 4 - reinstall it taking advantage of shamefully hoisting

`pnpm i`

#### 5 - run it using dev

`pnpm dev`

**Comment by boyney123** [comment]
Thanks for the work around @hoghweed 🙏

**Comment by mrfelton** [comment]
Setting `shamefully-hoist` in my pnpm workspace root also resolved the issue for me. But that causes other issues. Ideally a workaround would not be needed to get this working!

**Comment by boyney123** [comment]
Yeah I'm not really an expert in `pnpm` (although I use it mostly), I'm not sure what work is involved in supporting it without `shamefully-hoist`, if anyone has any ideas, love to get this working!

**Comment by carlosallexandre** [comment]
> Yeah I'm not really an expert in `pnpm` (although I use it mostly), I'm not sure what work is involved in supporting it without `shamefully-hoist`, if anyone has any ideas, love to get this working!

#1423 was one option =/

**Comment by boyney123** [comment]
> > Yeah I'm not really an expert in `pnpm` (although I use it mostly), I'm not sure what work is involved in supporting it without `shamefully-hoist`, if anyone has any ideas, love to get this working!
> 
> [#1423](https://github.com/event-catalog/eventcatalog/pull/1423) was one option =/

Yeah totally, I'm curious if there is/was a simpler option. I'd be amazed if supporting pnpm requires a reshuffle of folder structures and changes (400+).... but I could be wrong! I just havent had time to explore the problem space yet... and hunt for a simple solution (yet)...

Also if the issue continues to get more traction from more users, it could prioritize being done, but at the moment, there a ton of other things that need looking at, but will keep this open in case anyone finds a simple solution, or I can come back in the future to look 👍 , hope that makes sense

**Comment by boyney123** [comment]
Going to close this now ,please raise again if you still face issues.
