### ISSUE TITLE
Adding new Domain Data prevents site restart

### ISSUE THREAD

**Issue by cthornhill** [event-catalog/eventcatalog#262]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

If I add Domain Data - domain folders and the associated md files, I can not get EventCatalog to run again after the initial session stops. This happens if I use my own domains or the samples as documented, on both my Windows 10 and OSX systems.  On Windows and Mac, if I remove the new Domain directories and associated md files, I can get a clean restart. For the "first run" (when I just installed EventCatalog and started the site with "npm run dev" I can add and see my new Domains (and the md files in them), but after I stop the site, I can not get it to restart with this data in place, no matter what sort of "run" directive I use (dev, build or prod style run command). 

### Steps to reproduce

1. download and install EventCatalog per the instructions
2. Run EventCatalog from the directory created at install (I used both custom and default names to test - same results)
3. Follow the directions in the documents to "add Domains" (I used the doc default and my own domain names/events  - same results). Note you can add just the domain directories or go ahead and add domains and the associated events - same results)
4. You can now see and interact with your new domains in EventCatalog as long as you are in the "first run" (first execution of the run command for the product).
5. Stop npm at the command line.
6. Try to start EventCatalog from the command line again with either the "npm run dev" or any provided run script (the failure is the same).
7. For me on both Windows 10 and Mac OSX I get fatal errors when I try to run EventCatalog again.
8. On the Mac, deleting the new domain structure does not appear to fix the error.
9. On Windows 11 deleting the new domain structures does appear to let me run again.

### Expected behavior

I expected that once new Domain Data was added it would be persistent and I could stop and start the server as needed.

### Actual behavior

Below is the Windows 10 Enterprise error from the console:
The version of Node is 16.5.0
The version of Yarn is 1.22.18

Fails to run again after adding domain “Orders” per the guide. Failure message is:
C:\Users\cthornhill-etc\ct-catalog>npm run dev

> [ct-catalog@0.0.1](mailto:ct-catalog@0.0.1) dev
> eventcatalog dev

> @eventcatalog/core@0.2.14 scripts:move-schema-for-download
> node scripts/move-schemas-for-download.js

node:fs:1405
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\cthornhill-etc\ct-catalog\domains\Orders\events'
    at Object.readdirSync (node:fs:1405:3)
    at getAllEventsAndSchemaPaths (C:\Users\cthornhill-etc\ct-catalog\.eventcatalog-core\scripts\move-schemas-for-download.js:5:22)
    at parseEventDirectory (C:\Users\cthornhill-etc\ct-catalog\.eventcatalog-core\scripts\move-schemas-for-download.js:26:33)
    at C:\Users\cthornhill-etc\ct-catalog\.eventcatalog-core\scripts\move-schemas-for-download.js:68:7
    at Array.forEach (<anonymous>)
    at main (C:\Users\cthornhill-etc\ct-catalog\.eventcatalog-core\scripts\move-schemas-for-download.js:67:13)
    at Object.<anonymous> (C:\Users\cthornhill-etc\ct-catalog\.eventcatalog-core\scripts\move-schemas-for-download.js:78:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Users\\cthornhill-etc\\ct-catalog\\domains\\Orders\\events'
}
Error: Command failed: cross-env PROJECT_DIR=C:\Users\cthornhill-etc\ct-catalog npm run scripts:move-schema-for-download
    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:899:15)
    at Command.<anonymous> (C:\Users\cthornhill-etc\ct-catalog\node_modules\@eventcatalog\core\bin\eventcatalog.js:85:5)
    at Command.listener [as _actionHandler] (C:\Users\cthornhill-etc\ct-catalog\node_modules\commander\index.js:922:31)
    at Command._parseCommand (C:\Users\cthornhill-etc\ct-catalog\node_modules\commander\index.js:1503:14)
    at Command._dispatchSubcommand (C:\Users\cthornhill-etc\ct-catalog\node_modules\commander\index.js:1443:18)
    at Command._parseCommand (C:\Users\cthornhill-etc\ct-catalog\node_modules\commander\index.js:1460:12)
    at Command.parse (C:\Users\cthornhill-etc\ct-catalog\node_modules\commander\index.js:1292:10)
    at run (C:\Users\cthornhill-etc\ct-catalog\node_modules\@eventcatalog\core\bin\eventcatalog.js:115:7) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 3608,
  stdout: null,
  stderr: null
}

Below are the errors from my Mac (OSX):
MacBook Air M1
OSX 12.2.1
Node v 16.15.0
Yarn v 3.2.0

cecilthornhill@M1-MacBook-Air my-catalog % npm run dev

> [my-catalog@0.0.1](mailto:my-catalog@0.0.1) dev
> eventcatalog dev

> @eventcatalog/core@0.2.14 scripts:move-schema-for-download
> node scripts/move-schemas-for-download.js

node:fs:1405
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir '/Users/cecilthornhill/my-catalog/domains/Orders/events'
    at Object.readdirSync (node:fs:1405:3)
    at getAllEventsAndSchemaPaths (/Users/cecilthornhill/my-catalog/.eventcatalog-core/scripts/move-schemas-for-download.js:5:22)
    at parseEventDirectory (/Users/cecilthornhill/my-catalog/.eventcatalog-core/scripts/move-schemas-for-download.js:26:33)
    at /Users/cecilthornhill/my-catalog/.eventcatalog-core/scripts/move-schemas-for-download.js:68:7
    at Array.forEach (<anonymous>)
    at main (/Users/cecilthornhill/my-catalog/.eventcatalog-core/scripts/move-schemas-for-download.js:67:13)
    at Object.<anonymous> (/Users/cecilthornhill/my-catalog/.eventcatalog-core/scripts/move-schemas-for-download.js:78:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/cecilthornhill/my-catalog/domains/Orders/events'
}
Error: Command failed: cross-env PROJECT_DIR=/Users/cecilthornhill/my-catalog npm run scripts:move-schema-for-download
    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:899:15)
    at Command.<anonymous> ([/Users/cecilthornhill/my-catalog/node_modules/@eventcatalog/core/bin/eventcatalog.js:85:5](mailto:/Users/cecilthornhill/my-catalog/node_modules/@eventcatalog/core/bin/eventcatalog.js:85:5))
    at Command.listener [as _actionHandler] (/Users/cecilthornhill/my-catalog/node_modules/commander/index.js:922:31)
    at Command._parseCommand (/Users/cecilthornhill/my-catalog/node_modules/commander/index.js:1503:14)
    at Command._dispatchSubcommand (/Users/cecilthornhill/my-catalog/node_modules/commander/index.js:1443:18)
    at Command._parseCommand (/Users/cecilthornhill/my-catalog/node_modules/commander/index.js:1460:12)
    at Command.parse (/Users/cecilthornhill/my-catalog/node_modules/commander/index.js:1292:10)
    at run ([/Users/cecilthornhill/my-catalog/node_modules/@eventcatalog/core/bin/eventcatalog.js:115:7](mailto:/Users/cecilthornhill/my-catalog/node_modules/@eventcatalog/core/bin/eventcatalog.js:115:7)) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 16268,
  stdout: null,
  stderr: null
}

### Your environment

- EventCatalog version used:
- "name": 
"my-catalog",
"version": 
"0.0.1",
"lockfileVersion": 
2,
"requires": 
true,
"packages": {
"": {
"name": 
"my-catalog",
"version": 
"0.0.1",
"dependencies": {
"@eventcatalog/core":
"0.2.14"
},
"devDependencies": {
"@eventcatalog/types":
"0.1.3",
"@types/node": 
"17.0.31",
"@types/react": 
"18.0.8",
"autoprefixer": 
"^10.4.0",
"cross-env": 
"^7.0.3",
"postcss": 
"^8.3.11",
"tailwindcss": 
"^2.2.19",
"typescript": 
"^4.4.4"
}

- Environment name and version (e.g. Chrome 89, Node.js 16.4): 
- WINDOWS
- Node is 16.5.0
- Yarn is 1.22.18
- Microsoft Edge 101.0.1210.32 (Official Build) (64-bit)
- MAC
- Node v 16.15.0
- Yarn v 3.2.0
-Safari v 15.3 (17612.4.9.1.8)
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):
- Windows 10 Enterprise LTSC Version 1809 OS Build 17763.2803
- OSX 12.2.1

**Comment by cthornhill** [comment]
I just retested on my Mac and verified the error when I only added the "Orders" Domain Dir and the required index.md file (I used the copy from the doc's to do this test with). I have also tried when adding Events (from the docs and custom) and I get the same error. If there is anything I can do to help please just ask, I look forward to working with EventCatalog and apologize I did not have time to actually try and code debug.

**Comment by cthornhill** [comment]
I was able to test the changes made to the code for ventcatalog/core": "0.2.18". They resolve the bug and I am now able to add Domains and Events under them and still stop the server and restart it with "npm run dev".  I do see some debug messages when I run the new versions and they appear to relate to this issue: "autoprefixer: Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated." I can post more if needed, but I was guessing the debug was intentional for now and the warnings are expected at this point. Many thanks for the fix as it lets me continue working to build a customer demo for EventCatalog. I do hope to work on cleaning up deprecated modules, and run time output eventually, but those are all more or less "config" issues for later.

**Comment by boyney123** [comment]
Closing this issue.

EventCatalog v2 is being released, and no longer an issue.

If you still experience any of these issues, please raise a new ticket. 

Thank you!
