### ISSUE TITLE
v2 does not start in dev on windows

### ISSUE THREAD

**Issue by wliew99** [event-catalog/eventcatalog#547]
# Summary
Fresh setup of v2 event catalog on windows.  After `npm install` tried to `npm run dev` and it failed.
The same operation works on ubuntu.

# Expected behavior
`npm run dev` starts and localhost:3000 to launch

# Actual behavior
`Error: Command failed: PROJECT_DIR='C:\Users\hellotika\eventcatalog' CATALOG_DIR='C:\Users\hellotika\eventcatalog\.eventcatalog-core' npm run dev
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at _Command.<anonymous> (C:\Users\hellotika\eventcatalog\node_modules\@eventcatalog\core\bin\dist\eventcatalog.cjs:3121:42)
    at _Command.listener [as _actionHandler] (C:\Users\hellotika\eventcatalog\node_modules\@eventcatalog\core\bin\dist\eventcatalog.cjs:1443:21)
    at C:\Users\hellotika\eventcatalog\node_modules\@eventcatalog\core\bin\dist\eventcatalog.cjs:2233:24
    at _Command._chainOrCall (C:\Users\hellotika\eventcatalog\node_modules\@eventcatalog\core\bin\dist\eventcatalog.cjs:2141:16)
    at _Command._parseCommand (C:\Users\hellotika\eventcatalog\node_modules\@eventcatalog\core\bin\dist\eventcatalog.cjs:2231:31)
    at C:\Users\hellotika\eventcatalog\node_modules\@eventcatalog\core\bin\dist\eventcatalog.cjs:2042:31 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 25560,
  stdout: null,
  stderr: null
}

Node.js v20.15.0`

👈

**Comment by Joaopmb** [comment]
Same error here

Node.Js v20.15.1
npm 10.7.0

**Comment by mattiasclaesson** [comment]
Same issue, used  npx @eventcatalog/create-eventcatalog@latest to create.

Both "npm run dev" and "npm run build", fail int he same way.

**Comment by boyney123** [comment]
Thanks, this should be fixed in @eventcatalog/core@2.0.30 now, let us know if you still have issues. Thanks to @carlosallexandre for the fix.
