### ISSUE TITLE
npm run build faild in docker container with node 20.17 npm 10.8.2 without proxy or internet

### ISSUE THREAD

**Issue by remcocats** [event-catalog/eventcatalog#978]
### I tried this:

when I run the npm build after een npm ci I get this error:

### This happened:

15:42:49 [ERROR] [vite] x Build failed in 3.02s
transforming (427) [../node_modules/@heroicons/react/20/solid/esm/UserGroupIcon.js[vite](mailto:../node_modules/@heroicons/react/20/solid/esm/UserGroupIcon.js%5bvite)]: Rollup failed to resolve import "@stoplight/markdown-viewer" from [/pub/node_modules/@stoplight/json-schema-viewer/index.mjs](mailto:/pub/node_modules/@stoplight/json-schema-viewer/index.mjs).
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
  Stack trace:
    at viteWarn (file:///pub/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:65589:17)
    at onRollupWarning (file:///pub/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:65619:5)
    at file:///pub/node_modules/rollup/dist/es/shared/node-entry.js:19475:13
    at ModuleLoader.handleInvalidResolvedId (file:///pub/node_modules/rollup/dist/es/shared/node-entry.js:20090:26)
npm verbose cwd /pub/.eventcatalog-core
npm verbose os Linux 4.18.0-553.22.1.el8_10.x86_64
npm verbose node v20.17.0
npm verbose npm  v10.8.2
npm verbose exit 1
npm verbose code 1
node:internal/errors:984
  const err = new Error(message);
              ^
 
Error: Command failed: cross-env PROJECT_DIR='/pub' CATALOG_DIR='/pub/.eventcatalog-core' npm run build
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:891:11)
    at execSync (node:child_process:963:15)
    at Command.<anonymous> ([/pub/node_modules/@eventcatalog/core/bin/dist/eventcatalog.cjs:535:42](mailto:/pub/node_modules/@eventcatalog/core/bin/dist/eventcatalog.cjs:535:42))
    at async Command.parseAsync (/pub/node_modules/commander/lib/command.js:1092:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 435,
  stdout: null,
  stderr: null
}

### I expected this:

that the build succeded

### Is there a workaround?

I'm still searching for a workaround

### Platform(s)

Linux

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by hartmanjan1970** [comment]
the bug seems to be fixed with the following addition of the stoplight dependencies:
```javascript
  "dependencies": {
    "@eventcatalog/core": "2.14.2",
    "@eventcatalog/generator-asyncapi": "^2.7.1",
    "@stoplight/markdown-viewer": "^5.7.1",
    "@stoplight/mosaic-code-viewer": "^1.53.4",
    "deasync": "^0.1.30"
  }
```

**Comment by glc-omid** [comment]
The actual used stoplight version has the >=20.10 node constraint 
i think this must be upgraded in EC 

need to have a look

**Comment by carlosallexandre** [comment]
Hey,

With the merge of PR #1110, is this issue resolved?

**Comment by boyney123** [comment]
Going to close this now ,please raise again if you still face issues.
